name: Update terraform dependencies
on:
  schedule:
    # run everyday at 6
    - cron:  '0 6 * * *'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: patrickjahns/dependabot-terraform-action@v1
